# The URL the site will be built for
base_url = "https://kafkiansky.github.io"
title = "kafkiansky.dev"

# The site theme to use.
theme = "adidoks"

# The default language; used in feeds and search index
# Note: the search index doesn't support Chinese/Japanese/Korean Languages
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to generate a feed file for the site
generate_feed = true
feed_filename = "rss.xml"

# When set to "true", the generated HTML files are minified.
minify_html = false

# The taxonomies to be rendered for the site and their configuration.
taxonomies = [
  {name = "authors"},
  {name = "tags"},
]

# Whether to build a search index to be used later on by a JavaScript library
# When set to "true", a search index is built from the pages and section
# content for `default_language`.
build_search_index = true

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the rendered content of the page/section in the index
include_content = true

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[markdown]
# Whether to do syntax highlighting.
# Theme can be customised by setting the `highlight_theme`
# variable to a theme supported by Zola
highlight_code = true
highlight_theme = "GitHub"
#highlight_theme = "inspired-github"
# highlight_theme = "cheerfully-light"
extra_syntaxes_and_themes = ["syntaxes"]

[extra]
# Put all your custom variables here
author = "V Zanfir"
github = "https://github.com/kafkiansky"
email = "vadimzanfir@gmail.com"
# Set HTML file language
language_code = "ru-RU"

# Set theme-color meta tag for Chrome browser
theme_color = "#fff"


# Set date format in blog publish metadata
timeformat = "%B %e, %Y" # e.g. June 14, 2021
timezone = "Europe/Moscow"

# Edit page on reposity or not
edit_page = false
repo_branch = "master"

## Math settings
# options: true, false. Enable math support globally,
# default: false. You can always enable math on a per page.
math = false
library = "katex"  # options: "katex", "mathjax". default is "katex".

## JSON-LD
[extra.schema]
type = "Person"
logo = "logo-doks.png"
linked_in = ""
github = "https://github.com/kafkiansky"
section = "blog" # see config.extra.main~url
## Sitelinks Search Box
site_links_search_box = false

[[extra.menu.social]]
name = "GitHub"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>'
url = "https://github.com/kafkiansky"
post = "v0.1.0"
weight = 20

[page]
toc = true

[section]
toc = true